### ISSUE TITLE
total amount of coins (balance) showing incorrect results (Coldstaking node)

### ISSUE THREAD

**Issue by SativaL** [dasource/partyman#15]
why is partyman not showing the correct watchonly total balance ? it only shows the amount of coins that arent staking atm i think
because for example you have 10500 coins
it will say total amount balance is 9500
but in reality its 10500
getinfo and status same results
seems like it is not possible to check the absolute total amount of all coins in your wallet from your coldstaking node ? if yes.. how ?

**Comment by dasource** [comment]
A cold staking node is not connected to your wallet, therefore it has no ability to detect your balance other than by which coins have been enabled for cold staking (as it can read this from the blockchain).

If your balance is 10,500 in your wallet but Cold Staking Node is showing 9,000 that means either a. the node is not fully synced, hence not accurate or b. only 9000 out of 10500 are cold staking to this Staking Node.
