### ISSUE TITLE
Reset reward address to Default

### ISSUE THREAD

**Issue by joefiorello** [dasource/partyman#19]
Is there a way to reset the reward address back to the default so the coins go directly into cold staking?  I changed this to my copay wallet address and would like to change it back.

**Comment by dasource** [comment]
If you pull the latest release then this has been fixed. If you simply leave the reward address blank it will clear it.

6d0a0a3

**Comment by joefiorello** [comment]
Perfect thank you!

**Comment by joefiorello** [comment]
I've set this back to default and even shows as such on partyman, but the stake reward was still send to the previous address.

articl@partjoe1:~/partyman$ ./partyman stakingnode rewardaddress
partyman version 0.10 - Wed May 15 18:18:15 UTC 2019
gathering info, please wait...   done!
 --> checking wallet ...  done!
 --> checking for existing reward address config ...  done!
 --> Current Reward Address : default mode
** Your wallet is configured in default mode - it will send the staking rewards back to the staking address.
