### ISSUE TITLE
/partyman/lib/functions.sh: line 344: [: !=: unary operator expected

### ISSUE THREAD

**Issue by minskmaz** [dasource/partyman#2]
Here's the Dockerfile:

FROM ubuntu:16.04
#FROM ludx/particl

RUN apt-get update -y
RUN apt-get upgrade -y

RUN apt-get install -y python git curl unzip pv jq netcat sed
RUN apt-get install -y build-essential libtool autotools-dev automake pkg-config bsdmainutils curl
RUN apt-get install -y netcat-openbsd
RUN echo '0' | update-alternatives --config nc

ENV TERM=xterm
RUN git clone https://github.com/dasource/partyman
RUN cd partyman && ./partyman install

**Comment by dasource** [comment]
Grab the latest 1664ee535415cee7263717abdd0703bc70e26ef2 and run install like this `./partyman install unattended`
