### ISSUE TITLE
I've set this back to default and even shows as such on partyman, but the stake reward was still send to the previous address.

### ISSUE THREAD

**Issue by joefiorello** [dasource/partyman#20]
I've set this back to default and even shows as such on partyman, but the stake reward was still send to the previous address.

articl@partjoe1:~/partyman$ ./partyman stakingnode rewardaddress
partyman version 0.10 - Wed May 15 18:18:15 UTC 2019
gathering info, please wait...   done!
 --> checking wallet ...  done!
 --> checking for existing reward address config ...  done!
 --> Current Reward Address : default mode
** Your wallet is configured in default mode - it will send the staking rewards back to the staking address.

_Originally posted by @joefiorello in https://github.com/dasource/partyman/issues/19#issuecomment-492766734_

**Comment by dasource** [comment]
You will need to restart the darmon after making this change. There is a ommit which fixes this behaviour and it should be in the next release 0.18.0.8+ 

For now though, a restart is required.
