### ISSUE TITLE
Status page not displaying stats properly when connected via Tor

### ISSUE THREAD

**Issue by bacoinin** [dasource/partyman#25]
The status page is not displaying some info correctly when Particl daemon is running via Tor:
A. Particl bind ip address: (shows the public IP)
B. particld connection count: (shows 0)

Fix A: Check if running via Tor and if yes use getlocalnetwork["localaddreses"]["address"]

Fix B:
Change 
```
PARTYD_CONNECTIONS=$(netstat -nat | grep ESTA | grep -c 51738);                                         
```
to
```
PARTYD_CONNECTIONS=$("$PARTY_CLI" getconnectioncount 2>/dev/null);
```

**Comment by dasource** [comment]
This should be fixed with above merge, any issues re-open. Thanks.

**Comment by bacoinin** [comment]
No its not.
