### ISSUE TITLE
Systemd script incompatibility

### ISSUE THREAD

**Issue by vivook** [dasource/partyman#31]
Partyman clones particl-core to 'particlcore'. But the particld.service in [particl-core](https://github.com/particl/particl-core/blob/master/contrib/init/particld.service#L11) expects to find particld in `/home/particl/Particl`, so it fails to run.

Partyman should clone particl-core into `/home/particl/Particl`

**Comment by dasource** [comment]
Thanks, ill take a look at this.

**Comment by nkvr62** [comment]
I have submitted a PR that should address this issue, though not in the way originally described by @vivook 
[https://github.com/dasource/partyman/pull/36](url)
