### ISSUE TITLE
Partyman status fails on ubuntu

### ISSUE THREAD

**Issue by vivook** [dasource/partyman#38]
On ubuntu, the pidfile is written to `$DATA_DIR/particld.pid`, not `$DATA_DIR/particl.pid`, so partyman doesn't work properly. [This line](https://github.com/dasource/partyman/blob/master/lib/functions.sh#L1369) needs fixing.

**Comment by dasource** [comment]
This should be fixed on new installs using the recent PR merges. Thank you.
